export type Hex = `0x${string}`;
export type Address = `0x${string}`;

export interface Attestation {
  skillHash: Hex;
  auditCriteriaHash: Hex;
  zkProof: Hex;
  auditorCommitment: Hex;
  stakeAmount: bigint;
  timestamp: bigint;
  auditLevel: number;
}

export interface AuditorReputation {
  score: bigint;
  totalStake: bigint;
  attestationCount: bigint;
}

export interface DisputeInfo {
  skillHash: Hex;
  attestationIndex: bigint;
  evidence: Hex;
  challenger: Address;
  bond: bigint;
  resolved: boolean;
  auditorFault: boolean;
}

export interface UnstakeRequest {
  amount: bigint;
  unlockTimestamp: bigint;
}

export interface BountyInfo {
  publisher: Address;
  amount: bigint;
  requiredLevel: number;
  expiresAt: bigint;
  claimed: boolean;
}

export interface AegisConfig {
  /** Target chain ID (8453 for Base) */
  chainId: number;
  /** AegisRegistry contract address (optional — auto-resolved from built-in addresses for supported chains) */
  registryAddress?: Address;
  /** RPC URL (optional — defaults to public RPC for the chain) */
  rpcUrl?: string;
}

/**
 * Parameters for registering a skill attestation on the AEGIS Registry.
 *
 * **Prerequisites:**
 * 1. The `auditorCommitment` must already be registered on-chain via `registerAuditor()`.
 *    Unregistered auditors will cause the transaction to revert with `AuditorNotRegistered`.
 * 2. The ZK proof must be valid — it is verified on-chain by the UltraHonk verifier.
 *    Invalid proofs revert with `InvalidProof`.
 * 3. A registration fee of 0.001 ETH must be sent with the transaction.
 *
 * **Common revert errors:**
 * - `InvalidAuditLevel` (0x657f08f5) — auditLevel must be exactly 1, 2, or 3
 * - `AuditorNotRegistered` (0x57fb4f95) — auditorCommitment not registered on-chain
 * - `InvalidProof` (0x09bde339) — ZK proof verification failed
 * - `InsufficientFee` (0x025dbdd4) — msg.value < 0.001 ETH
 */
export interface RegisterSkillParams {
  /** keccak256 hash of the skill/plugin source code (bytes32) */
  skillHash: Hex;
  /** IPFS URI, HTTP URL, or data URI for the skill metadata JSON. Can be empty string if no metadata. Use `metadataToDataURI()` to encode inline without needing IPFS. */
  metadataURI: string;
  /** UltraHonk ZK proof generated by the Noir circuit (hex-encoded bytes) */
  attestationProof: Hex;
  /** Public inputs array: [skillHash, criteriaHash, auditLevelHex, auditorCommitment] — order must match the circuit */
  publicInputs: Hex[];
  /** The Pedersen commitment of the auditor who produced the proof. MUST be registered on-chain first via registerAuditor(). */
  auditorCommitment: Hex;
  /**
   * Audit tier level. **MUST be 1, 2, or 3** — any other value reverts with `InvalidAuditLevel` (0x657f08f5).
   * - `1` = L1 Functional — automated security scan
   * - `2` = L2 Robust — static + dynamic analysis
   * - `3` = L3 Security — full manual audit
   */
  auditLevel: 1 | 2 | 3;
  /** Address to receive bounty payout if one exists for this skill (defaults to 0x0 to skip) */
  bountyRecipient?: Address;
  /** Registration fee in wei (default: 0.001 ETH = 1000000000000000n). Must be >= 0.001 ETH or tx reverts with InsufficientFee. */
  fee?: bigint;
}

export interface SubmitAttestationParams {
  sourceCode: Uint8Array;
  auditResults: Uint8Array;
  auditorPrivateKey: string;
  skillHash: Hex;
  auditLevel: 1 | 2 | 3;
  metadataURI: string;
}

// ──────────────────────────────────────────────
//  Skill Listing Types
// ──────────────────────────────────────────────

/**
 * Parameters for listing a skill on the AEGIS Registry (no audit required).
 *
 * This is the lightweight alternative to `registerSkill()` — it lets anyone
 * list a skill for future auditing without needing an auditor or ZK proof.
 *
 * **Requirements:**
 * - `skillHash` must not be zero
 * - `metadataURI` must not be empty (provide skill name, description, version)
 * - A listing fee of 0.001 ETH must be sent with the transaction
 * - The skill must not already be listed
 *
 * **Common revert errors:**
 * - `InvalidSkillHash` (0xd556b563) — skillHash is bytes32(0)
 * - `EmptyMetadata` (0xae921357) — metadataURI is empty
 * - `InsufficientListingFee` (0xbf8513a4) — msg.value < 0.001 ETH
 * - `SkillAlreadyListed` (0x8046aa2c) — skill already has a listing
 */
export interface ListSkillParams {
  /** keccak256 hash of the skill/plugin source code (bytes32) */
  skillHash: Hex;
  /** URI pointing to skill metadata JSON (IPFS, HTTP, or data URI). Cannot be empty. Use `metadataToDataURI()` to encode inline. */
  metadataURI: string;
  /** Listing fee in wei (default: 0.001 ETH = 1000000000000000n). Must be >= 0.001 ETH or tx reverts. */
  fee?: bigint;
}

/** On-chain skill listing data */
export interface SkillListing {
  /** Address that listed the skill */
  publisher: Address;
  /** Metadata URI for the skill */
  metadataURI: string;
  /** Block timestamp of when the skill was listed */
  timestamp: bigint;
  /** Whether the skill is listed */
  listed: boolean;
}

// ──────────────────────────────────────────────
//  Event Types — for discovery & history queries
// ──────────────────────────────────────────────

export interface SkillListedEvent {
  skillHash: Hex;
  publisher: Address;
  metadataURI: string;
  blockNumber: bigint;
  transactionHash: Hex;
}

export interface SkillRegisteredEvent {
  skillHash: Hex;
  auditLevel: number;
  auditorCommitment: Hex;
  blockNumber: bigint;
  transactionHash: Hex;
}

export interface AuditorRegisteredEvent {
  auditorCommitment: Hex;
  stake: bigint;
  blockNumber: bigint;
  transactionHash: Hex;
}

export interface DisputeOpenedEvent {
  disputeId: bigint;
  skillHash: Hex;
  blockNumber: bigint;
  transactionHash: Hex;
}

export interface DisputeResolvedEvent {
  disputeId: bigint;
  auditorSlashed: boolean;
  blockNumber: bigint;
  transactionHash: Hex;
}

export interface AttestationRevokedEvent {
  skillHash: Hex;
  attestationIndex: bigint;
  auditorCommitment: Hex;
  blockNumber: bigint;
  transactionHash: Hex;
}

/** Full dispute details from the contract's getDispute() getter */
export interface DisputeDetails {
  disputeId: bigint;
  skillHash: Hex;
  attestationIndex: bigint;
  evidence: Hex;
  challenger: Address;
  bond: bigint;
  resolved: boolean;
  auditorFault: boolean;
}

/** Aggregated auditor profile combining reputation, attestation history, and dispute record */
export interface AuditorProfile {
  auditorCommitment: Hex;
  reputation: AuditorReputation;
  attestations: AuditorAttestationRecord[];
  disputes: AuditorDisputeRecord[];
  activeDisputeCount: bigint;
  registeredAt: bigint;
  registrationTxHash: Hex;
}

/** An attestation made by an auditor (from SkillRegistered event) */
export interface AuditorAttestationRecord {
  skillHash: Hex;
  auditLevel: number;
  blockNumber: bigint;
  transactionHash: Hex;
  revoked: boolean;
}

/** A dispute involving an auditor's attestation */
export interface AuditorDisputeRecord {
  disputeId: bigint;
  skillHash: Hex;
  attestationIndex: bigint;
  resolved: boolean;
  auditorFault: boolean;
  blockNumber: bigint;
  transactionHash: Hex;
}

export interface BountyPostedEvent {
  skillHash: Hex;
  amount: bigint;
  requiredLevel: number;
  expiresAt: bigint;
  blockNumber: bigint;
  transactionHash: Hex;
}

export interface BountyClaimedEvent {
  skillHash: Hex;
  recipient: Address;
  auditorPayout: bigint;
  protocolFee: bigint;
  blockNumber: bigint;
  transactionHash: Hex;
}

// ──────────────────────────────────────────────
//  ERC-8004 (Trustless Agents) Integration Types
// ──────────────────────────────────────────────

/** ERC-8004 validation status for a request */
export interface ValidationStatus {
  validator: Address;
  agentId: bigint;
  response: number; // 0-100 score
  responseHash: Hex;
  tag: string;
  timestamp: bigint;
}

/** Aggregated validation summary from ERC-8004 ValidationRegistry */
export interface ValidationSummary {
  count: bigint;
  averageResponse: number;
}

/** Aggregated reputation summary from ERC-8004 ReputationRegistry */
export interface ReputationSummary {
  count: bigint;
  summaryValue: bigint;
  summaryValueDecimals: number;
}

/** ERC-8004 agent registration data */
export interface AgentRegistration {
  name: string;
  description: string;
  agentURI: string;
  services?: Array<{
    type: string;
    endpoint: string;
    description?: string;
  }>;
  skills?: Array<{
    skillHash: Hex;
    auditLevel?: number;
    metadataURI?: string;
  }>;
  x402Support?: {
    paymentAddress: Address;
    acceptedTokens: Address[];
  };
}

/**
 * Parameters for requesting ERC-8004 validation (called by agent owner).
 * Step 1 of the two-wallet bridge flow.
 */
export interface RequestErc8004ValidationParams {
  /** The ERC-8004 agent ID */
  agentId: bigint;
  /** The AEGIS skill hash to bridge */
  skillHash: Hex;
  /** AEGIS audit level (1=Functional, 2=Robust, 3=Security) */
  auditLevel: 1 | 2 | 3;
  /** URI to the audit metadata (e.g. IPFS CID) */
  metadataURI: string;
  /** Address of the AEGIS validator who will respond */
  validatorAddress: Address;
}

/**
 * Parameters for responding to an ERC-8004 validation (called by AEGIS validator).
 * Step 2 of the two-wallet bridge flow.
 */
export interface RespondToErc8004ValidationParams {
  /** The request hash (returned from requestErc8004Validation) */
  requestHash: Hex;
  /** The ERC-8004 agent ID (for optional reputation feedback) */
  agentId: bigint;
  /** The AEGIS skill hash */
  skillHash: Hex;
  /** AEGIS audit level (1=Functional, 2=Robust, 3=Security) */
  auditLevel: 1 | 2 | 3;
  /** URI to the audit metadata (e.g. IPFS CID) */
  metadataURI: string;
  /** Also submit reputation feedback to ERC-8004 ReputationRegistry (default: true) */
  includeReputation?: boolean;
}

// ──────────────────────────────────────────────
//  x402 Payment Types
// ──────────────────────────────────────────────

/** x402 payment requirement returned in HTTP 402 responses */
export interface X402PaymentRequirement {
  scheme: string;
  network: string;
  maxAmountRequired: string;
  resource: string;
  description: string;
  mimeType?: string;
  payTo: Address;
  maxTimeoutSeconds?: number;
  asset: Address;
  extra?: Record<string, unknown>;
}

/** Configuration for an auditor's x402-enabled endpoint */
export interface X402AuditorConfig {
  /** Auditor's wallet address to receive payments */
  paymentAddress: Address;
  /** Price per audit in USDC (6 decimals, e.g. "5.00" = 5 USDC) */
  priceUsdc: string;
  /** Supported audit levels */
  supportedLevels: Array<1 | 2 | 3>;
  /** Optional description for the x402 payment requirement */
  description?: string;
}

// ──────────────────────────────────────────────
//  Trust Profile Types
// ──────────────────────────────────────────────

/** Trust level classification based on composite score */
export type TrustLevel = 'unknown' | 'basic' | 'verified' | 'trusted';

/** Individual attestation within a SkillTrustScore */
export interface SkillAttestation {
  /** Auditor's ZK commitment hash */
  auditorCommitment: Hex;
  /** AEGIS audit level (1=Functional, 2=Robust, 3=Security) */
  auditLevel: number;
  /** Block timestamp of the attestation */
  timestamp: bigint;
  /** Whether the ZK proof verifies on-chain */
  verified: boolean;
}

/** Trust data for a single skill attestation */
export interface SkillTrustScore {
  /** The bytes32 skill hash */
  skillHash: Hex;
  /** Metadata URI (IPFS or HTTP) */
  metadataURI: string;
  /** All attestations for this skill */
  attestations: SkillAttestation[];
  /** Highest audit level among attestations */
  highestLevel: number;
  /** Total number of disputes opened against this skill */
  disputeCount: number;
  /** Whether any disputes are still unresolved */
  hasActiveDisputes: boolean;
}

/** Aggregated trust profile for an AI agent */
export interface TrustProfile {
  /** ERC-8004 agent identity ID */
  agentId: bigint;
  /** Agent identity info from ERC-8004 IdentityRegistry */
  identity: {
    owner: Address;
    agentURI: string;
  };
  /** Per-skill trust breakdown */
  skills: SkillTrustScore[];
  /** Aggregated ERC-8004 validation data */
  validation: {
    count: bigint;
    averageScore: number;
  };
  /** Aggregated ERC-8004 reputation data */
  reputation: {
    count: bigint;
    summaryValue: bigint;
    summaryValueDecimals: number;
  };
  /** Computed overall trust assessment */
  overall: {
    /** Composite trust score (0-100) */
    trustScore: number;
    /** Trust level classification */
    level: TrustLevel;
    /** Number of audited skills */
    skillCount: number;
    /** Highest audit level across all skills */
    highestAuditLevel: number;
    /** Whether any skill has unresolved disputes */
    hasActiveDisputes: boolean;
  };
  /** ISO 8601 timestamp of when the profile was computed */
  timestamp: string;
}

/** USDC pricing for trust API endpoints */
export interface TrustApiPricing {
  /** Price per single profile query (e.g. "0.10" = 10 cents) */
  profileQuery: string;
  /** Price per single skill trust query (e.g. "0.05") */
  skillQuery: string;
  /** Price per batch profile query (e.g. "0.50") */
  batchQuery: string;
}

/** Configuration for the x402-gated Trust API server */
export interface TrustApiConfig {
  /** Wallet address to receive USDC payments */
  paymentAddress: Address;
  /** Chain ID (8453 for Base) */
  chainId: number;
  /** Optional custom RPC URL */
  rpcUrl?: string;
  /** Optional explicit AegisRegistry address */
  registryAddress?: Address;
  /** USDC pricing per endpoint */
  pricing: TrustApiPricing;
  /** Optional description for x402 payment requirements */
  description?: string;
}

/** Typed client for consuming the x402-gated Trust API */
export interface TrustApiClient {
  /** Get a full trust profile for an agent */
  getProfile(agentId: bigint): Promise<TrustProfile>;
  /** Get trust data for a single skill */
  getSkillTrust(skillHash: Hex): Promise<SkillTrustScore>;
  /** Get trust profiles for multiple agents in one request */
  batchProfiles(agentIds: bigint[]): Promise<TrustProfile[]>;
}
